const traducciones = {
    es: {
      titulo_banner: "¡Bienvenidos!",
      nombre: "Soy Sthephanie León Vargas",
      saludo: "Es un gusto que visites mi portafolio.",
      perfilProfesional: "Desarrolladora de aplicaciones de escritorio y web, especializada en el desarrollo Full-Stack, con experiencia en lenguaje Java, manejo de bases de datos relacionales como Oracle, Sql Server, MySQL, y creación de páginas con HTML y CSS.",
      perfilProfesionalTitulo: "Perfil Profesional",
      misionTitulo: "Misión",
      mision: "Satisfacer las necesidades de los usuarios, creando aplicaciones eficientes que faciliten las tareas dentro de la empresa, creando así un impacto positivo en la mejora e innovación de los procesos requeridos.",
      visionTitulo: "Visión",
      vision: "Demostrar mi pasión por implementar nuevas ideas en base a flujos de trabajo que pueda necesitar la empresa, llevando a cabo el desarrollo y administración de proyectos nuevos.",
      valoresTitulo: "Valores Personales",
      valoresDesc: "A continuación, describo los valores que me identifican como persona.",
      lealtadTitulo: "Lealtad",
      lealtad: "Mantengo la confianza y discreción con mis compañeros de trabajo.",
      honestidadTitulo:"Honestidad",
      honestidad:"Me comprometo a siempre decir la verdad para establecer confianza",
      humildadTitulo:"Humildad",
      humildad:"Reconozco mis errores y acepto las retroalimentaciones que me puedan dar, para mejorar cada día.",
      perseveranciaTitulo:"Perseverancia",
      perseverancia:"Cumplir con los trabajos propuestos, incluso cuando hayan obstáculos en el camino o retos nuevos, siempre estoy dispuesta a seguir hasta el final para cumplir los objetivos.",
      //respetoTitulo:"Respeto",
      //respeto:"Mantener el respeto con todas las personas por igual, creando un espacio de trabajo positivo y en el que todos nos sentimos cómodos como equipo.",
      habilidadesTitulo:"Habilidades",
      habilidadesDesc:"En esta sección puedes ver mis habilidades blandas y tecnicas que me caracterizan e implemento en mi día a día.",
      habilidadesBlandasT:"Habilidades Blandas",
      comunicacion:"Comunicación",
      empatia:"Empatía",
      trabajoEquipo:"Trabajo en Equipo",
      toleancia:"Tolerancia",
      habilidadesTecnicasT:"Habilidades Técnicas",
      proyectosTitulo:"Proyectos",
      proyectosDesc:"En esta sección, puedes observar algunos de los proyectos que realizado en la univerdad algunos proyectos fueron realizados en equipo y otros de forma Individual.",
      aplicacionEscritorio:"Aplicación de Escritorio",
      cursoPOO:"Curso: Programación Orientada a Objetos",
      cursoPOODesc:"Sistema para el mantenimiento de un aeropuerto, en el cual se ingresa y almacena la información referente a los vuelos.",
      proyectoIndividual:"Proyecto Individual",
      sitioWeb:"Sitio Web",
      CursoProyecto1:"Curso: Proyecto de Ingieneria del Software 1",
      proyecto1Desc:"Sitio web para que los padres de familia puedan buscar el centro educativo ideal para sus hijos.",
      proyectoGrupal:"Proyecto Grupal",
      videoJuego:"Video Juego 2D",
      cursoPatrones:"Curso: Programación con Patrones",
      cursoPatronesDesc:" Es un juego de sprites 2D, con temática de aventuras y plataformas, consiste en ganar los niveles de cada zona del mapa y derrotar a los enemigos que aparezcan.",
      proyectoGrupal2:"Proyecto Grupal",
      contactosTitulo:"Contactos",
      contactosDesc:"¡Puedes contactame completando el siguiente formulario o también puedes visitar los enlaces!",
      nombreContacto:"Nombre",
      correoContacto:"Correo Electrónico",
      comentariosContacto:"Comentarios",
      enviarContacto:"Enviar",
      infoContacto:"Información adicional de contacto:",
      enlaces: "Enlaces",
      //barra menu
      menu_inicio:"Inicio",
      menu_perfil:"Mi Perfil",
      menu_habilidades:"Habilidades",
      menu_protectos:"Proyectos",
      menu_contactos:"Contactos",
    },
    en: {
      titulo_banner: "Welcome!",
      nombre: "I am Sthephanie León Vargas",
      saludo: "It's a pleasure that you visit my portfolio.",
      perfilProfesional: "Desktop and web application developer, specializing in full-stack development, with experience in Java, relational database management such as Oracle, SQL Server, and MySQL, and page creation using HTML and CSS.",
      perfilProfesionalTitulo: "Professional Profile",
      misionTitulo: "Mission",
      mision: "Satisfy user needs by creating efficient applications that facilitate tasks within the company, thus creating a positive impact on the improvement and innovation of the required processes.",
      visionTitulo: "Vision",
      vision: "Demonstrate my passion for implementing new ideas based on workflows that the company may need, carrying out the development and management of new projects.",
      valoresTitulo: "Personal Values",
      valoresDesc: "Below, I describe the values ​​that identify me as a person.",
      lealtadTitulo: "Loyalty",
      lealtad: "I maintain trust and discretion with my coworkers.",
      honestidadTitulo:"Honesty",
      honestidad:"I commit to always telling the truth to establish trust.",
      humildadTitulo:"Modesty",
      humildad:"I acknowledge my mistakes and accept feedback so I can improve every day.",
      perseveranciaTitulo:"Perseverance",
      perseverancia:"To accomplish the proposed tasks, even when there are obstacles along the way or new challenges, I am always willing to follow through to the end to meet the objectives.",
      //respetoTitulo:"Respect",
      //respeto:"Maintain respect for everyone equally, creating a positive workspace where we all feel comfortable as a team.",
      habilidadesTitulo:"Skills",
      habilidadesDesc:"In this section, you can see the soft and technical skills that define me and that I implement in my daily life.",
      habilidadesBlandasT:"Soft Skills",
      comunicacion:"Communication",
      empatia:"Empathy",
      trabajoEquipo:"Teamwork",
      toleancia:"Tolerance",
      habilidadesTecnicasT:"Technical Skills",
      proyectosTitulo:"Projects",
      proyectosDesc:"In this section, you can see some of the projects I carried out at the university. Some projects were carried out as a team and others individually.",
      aplicacionEscritorio:"Desktop Application",
      cursoPOO:"Course: Object-Oriented Programming",
      cursoPOODesc:"System for airport maintenance, in which flight information is entered and stored.",
      proyectoIndividual:"Individual Project",
      sitioWeb:"Website",
      CursoProyecto1:"Course: Software Engineering Project 1",
      proyecto1Desc:"Website for parents to search for the ideal educational center for their children.",
      proyectoGrupal:"Group Project",
      videoJuego:"2D Video Game",
      cursoPatrones:"Course: Programming with Patterns",
      cursoPatronesDesc:"It is a 2D sprite game, with an adventure and platform theme, which consists of winning the levels in each area of ​​the map and defeating the enemies that appear.",
      proyectoGrupal2:"Group Project",
      contactosTitulo:"Contacts",
      contactosDesc:"You can contact me by filling out the form below or you can also visit the links!",
      nombreContacto:"Name",
      correoContacto:"Email",
      comentariosContacto:"Comments",
      enviarContacto:"Send",
      infoContacto:"Additional contact information:",
      enlaces: "Links:",
      //barra menu
      menu_inicio:"Home",
      menu_perfil:"My Profile",
      menu_habilidades:"Skills",
      menu_protectos:"Projects",
      menu_contactos:"Contacts"
    }
  };

  const switchIdioma = document.getElementById('idiomaSwitch');
  
  switchIdioma.addEventListener('change', function () {
    const idioma = this.checked ? 'en' : 'es';
    for (const id in traducciones[idioma]) {
      document.getElementById(id).textContent = traducciones[idioma][id];
    }
  });

